/**
 * puzzleService.ts — Client-side service for fetching pre-generated daily puzzles
 * and recording completions.
 *
 * Replaces the old client-side Gemini generation flow.
 * All puzzles come from the daily_puzzles table in Supabase,
 * pre-generated by the Edge Function cron.
 */

import { Category, Difficulty, GridSize, Puzzle } from "../types/puzzle.types";
import { supabase } from "./supabaseClient";

// ─── Types ───────────────────────────────────────────────────────────

/** Lightweight puzzle metadata for listing screens (no full grid data) */
export interface PuzzleMeta {
  id: string;
  category: Category;
  difficulty: Difficulty;
  gridSize: GridSize;
  variant: number;
  totalWords: number;
  estimatedTime: number;
  isCompleted: boolean;
  score: number | null;
  accuracy: number | null;
}

/** Data required to record a puzzle completion */
export interface CompletionData {
  puzzleId: string;
  userId: string;
  score: number;
  timeTaken: number;
  accuracy: number;
  hintsUsed: number;
  coinsEarned: number;
  puzzleDate: string;
  category: string;
  difficulty: string;
  gridSize: number;
}

// ─── Date helpers ────────────────────────────────────────────────────

/** Returns today's date in UTC as YYYY-MM-DD */
function getTodayUTC(): string {
  return new Date().toISOString().split("T")[0];
}

// ─── Puzzle fetching ─────────────────────────────────────────────────

/**
 * Fetches today's Daily Challenge puzzle metadata for the home screen.
 * Returns null if no Daily Challenge exists for today (e.g., cron hasn't run yet).
 */
export async function fetchDailyChallenge(): Promise<PuzzleMeta | null> {
  const today = getTodayUTC();

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select(
      "id, category, difficulty, grid_size, total_words, estimated_time, variant",
    )
    .eq("puzzle_date", today)
    .eq("is_daily_challenge", true)
    .single();

  if (error || !data) {
    console.warn(
      "[puzzleService] No daily challenge found for today:",
      error?.message,
    );
    return null;
  }

  return {
    id: data.id,
    category: data.category as Category,
    difficulty: data.difficulty as Difficulty,
    gridSize: data.grid_size as GridSize,
    variant: data.variant,
    totalWords: data.total_words,
    estimatedTime: data.estimated_time,
    isCompleted: false,
    score: null,
    accuracy: null,
  };
}

/**
 * Fetches all puzzle metadata for a given category today.
 * Returns lightweight cards for the category listing screen — no full puzzle data.
 *
 * Optionally checks completion status for a given user ID.
 */
export async function fetchCategoryPuzzles(
  category: Category,
  userId: string = "guest",
): Promise<PuzzleMeta[]> {
  const today = getTodayUTC();

  // Fetch today's puzzles for this category (metadata only, no puzzle_data)
  const { data: puzzles, error: puzzleError } = await supabase
    .from("daily_puzzles")
    .select(
      "id, category, difficulty, grid_size, variant, total_words, estimated_time",
    )
    .eq("puzzle_date", today)
    .eq("category", category)
    .eq("is_daily_challenge", false)
    .order("difficulty")
    .order("grid_size")
    .order("variant");

  if (puzzleError || !puzzles) {
    console.error(
      "[puzzleService] Failed to fetch category puzzles:",
      puzzleError?.message,
    );
    return [];
  }

  // Fetch user's completions for today's puzzles in this category
  const puzzleIds = puzzles.map((p) => p.id);
  const { data: completions } = await supabase
    .from("puzzle_completions")
    .select("puzzle_id, score, accuracy")
    .eq("user_id", userId)
    .in("puzzle_id", puzzleIds);

  const completionMap = new Map(
    (completions || []).map((c) => [
      c.puzzle_id,
      { score: c.score, accuracy: c.accuracy },
    ]),
  );

  return puzzles.map((p) => {
    const completion = completionMap.get(p.id);
    return {
      id: p.id,
      category: p.category as Category,
      difficulty: p.difficulty as Difficulty,
      gridSize: p.grid_size as GridSize,
      variant: p.variant,
      totalWords: p.total_words,
      estimatedTime: p.estimated_time,
      isCompleted: !!completion,
      score: completion?.score ?? null,
      accuracy: completion?.accuracy ?? null,
    };
  });
}

import { buildPuzzle } from "./crosswordEngine";

/**
 * Fetches the full puzzle data for a specific puzzle by ID.
 * The database only stores the word list and metadata.
 * We build the actual crossword grid layout here on the client.
 */
export async function fetchPuzzleById(
  puzzleId: string,
): Promise<Puzzle | null> {
  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("puzzle_data")
    .eq("id", puzzleId)
    .single();

  if (error || !data) {
    console.error("[puzzleService] Failed to fetch puzzle:", error?.message);
    return null;
  }

  // data.puzzle_data is the lightweight DailyPuzzleData
  const puzzleData = data.puzzle_data;
  if (!puzzleData || !puzzleData.words) return null;

  // Build the puzzle grid dynamically on the client
  return buildPuzzle(
    puzzleData.words,
    puzzleData.metadata.category || "general",
    puzzleData.metadata.difficulty || "medium",
    puzzleData.metadata.gridSize || 10,
  );
}

/**
 * Fetches a specific daily puzzle by its combination of parameters.
 * Useful as a fallback when the user navigates via the old generate screen flow.
 */
export async function fetchDailyPuzzle(
  category: Category,
  difficulty: Difficulty,
  gridSize: GridSize,
  variant: number = 1,
  date?: string,
): Promise<Puzzle | null> {
  const targetDate = date || getTodayUTC();

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("puzzle_data")
    .eq("puzzle_date", targetDate)
    .eq("category", category)
    .eq("difficulty", difficulty)
    .eq("grid_size", gridSize)
    .eq("variant", variant)
    .single();

  if (error || !data) {
    console.warn(
      `[puzzleService] No daily puzzle found for ${category}/${difficulty}/${gridSize}`,
    );
    return null;
  }

  const puzzleData = data.puzzle_data;
  if (!puzzleData || !puzzleData.words) return null;

  return buildPuzzle(puzzleData.words, category, difficulty, gridSize);
}

// ─── Completion recording ────────────────────────────────────────────

/**
 * Records a puzzle completion to the server.
 * Uses upsert to handle duplicate submissions gracefully.
 *
 * Called when the player finishes a puzzle. If offline, the caller
 * should queue this and retry when connectivity is restored.
 */
export async function recordCompletion(data: CompletionData): Promise<boolean> {
  const { error } = await supabase.from("puzzle_completions").upsert(
    {
      user_id: data.userId,
      puzzle_id: data.puzzleId,
      score: data.score,
      time_taken: data.timeTaken,
      accuracy: data.accuracy,
      hints_used: data.hintsUsed,
      coins_earned: data.coinsEarned,
      puzzle_date: data.puzzleDate,
      category: data.category,
      difficulty: data.difficulty,
      grid_size: data.gridSize,
      completed_at: new Date().toISOString(),
    },
    { onConflict: "user_id,puzzle_id" },
  );

  if (error) {
    console.error(
      "[puzzleService] Failed to record completion:",
      error.message,
    );
    return false;
  }

  return true;
}

/**
 * Fetches the user's recent completion history for the profile screen.
 * Returns the most recent completions with denormalized puzzle metadata.
 */
export async function fetchCompletionHistory(
  userId: string = "guest",
  limit: number = 20,
): Promise<CompletionData[]> {
  const { data, error } = await supabase
    .from("puzzle_completions")
    .select("*")
    .eq("user_id", userId)
    .order("completed_at", { ascending: false })
    .limit(limit);

  if (error || !data) {
    console.error("[puzzleService] Failed to fetch history:", error?.message);
    return [];
  }

  return data.map((row) => ({
    puzzleId: row.puzzle_id,
    userId: row.user_id,
    score: row.score,
    timeTaken: row.time_taken,
    accuracy: row.accuracy,
    hintsUsed: row.hints_used,
    coinsEarned: row.coins_earned,
    puzzleDate: row.puzzle_date,
    category: row.category,
    difficulty: row.difficulty,
    gridSize: row.grid_size,
  }));
}
