/**
 * puzzleService.ts — Client-side service for fetching pre-generated daily puzzles
 * and recording completions.
 *
 * Replaces the old client-side Gemini generation flow.
 * All puzzles come from the daily_puzzles table in Supabase,
 * pre-generated by the Edge Function cron.
 */

import { Category, Difficulty, GridSize, Puzzle } from "../types/puzzle.types";
import { supabase } from "./supabaseClient";

// ─── API Cache ───────────────────────────────────────────────────────

/**
 * Lightweight in-memory cache for API requests to minimize duplicate Supabase reads.
 * Configured for a 5-minute Time-To-Live (TTL).
 * Automatically clears when a puzzle is successfully completed.
 */
class ApiCache {
  private cache = new Map<string, { data: any; timestamp: number }>();
  private CACHE_TTL = 1000 * 60 * 5; // 5 minutes

  get<T>(key: string): T | null {
    const item = this.cache.get(key);
    if (!item) return null;
    if (Date.now() - item.timestamp > this.CACHE_TTL) {
      this.cache.delete(key);
      return null;
    }
    return item.data as T;
  }

  set(key: string, data: any): void {
    this.cache.set(key, { data, timestamp: Date.now() });
  }

  clear(): void {
    this.cache.clear();
  }
}

export const puzzleCache = new ApiCache();

// ─── Types ───────────────────────────────────────────────────────────

/** Lightweight puzzle metadata for listing screens (no full grid data) */
export interface PuzzleMeta {
  id: string;
  category: Category;
  difficulty: Difficulty;
  gridSize: GridSize;
  variant: number;
  totalWords: number;
  estimatedTime: number;
  isCompleted: boolean;
  score: number | null;
  accuracy: number | null;
  timeTaken: number | null;
}

/** Data required to record a puzzle completion */
export interface CompletionData {
  puzzleId: string;
  userId: string;
  score: number;
  timeTaken: number;
  accuracy: number;
  hintsUsed: number;
  coinsEarned: number;
  puzzleDate: string;
  category: string;
  difficulty: string;
  gridSize: number;
}

/**
 * Returns today's date as YYYY-MM-DD in **UTC**.
 *
 * The GitHub Actions cron that generates puzzles always writes puzzle_date
 * using `new Date().toISOString().split('T')[0]` — which is a UTC date.
 * The client must query with the same UTC date to match the DB rows correctly.
 *
 * Using local device timezone (e.g. IST = UTC+5:30) would cause the app to
 * query for a date one day ahead of what the server actually stored, making
 * every puzzle appear missing until the next UTC midnight.
 */
function getTodayUTC(): string {
  return new Date().toISOString().split("T")[0];
}

/**
 * Returns yesterday's date as YYYY-MM-DD in **UTC**.
 * Used as a graceful fallback when today's UTC puzzles haven't been generated
 * yet (e.g. the cron job runs at 00:05 UTC and the user opens the app just
 * after UTC midnight before the job completes).
 */
function getYesterdayUTC(): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - 1);
  return d.toISOString().split("T")[0];
}

// ─── Puzzle fetching ─────────────────────────────────────────────────

/**
 * Fetches today's Daily Challenge puzzle metadata for the home screen.
 *
 * Resolution order:
 *  1. Today UTC with is_daily_challenge = true  (ideal)
 *  2. Yesterday UTC with is_daily_challenge = true  (cron delay fallback)
 *  3. Any puzzle from the most recent available date  (when the dedicated
 *     daily_challenge row was never generated, e.g. due to API rate limits)
 */
export async function fetchDailyChallenge(
  userId: string = "guest",
): Promise<PuzzleMeta | null> {
  const cacheKey = `daily_challenge_${userId}`;
  const cached = puzzleCache.get<PuzzleMeta>(cacheKey);
  if (cached) return cached;

  const today = getTodayUTC();
  const yesterday = getYesterdayUTC();

  // ── Step 1 & 2: Try today then yesterday for a proper daily-challenge row ──
  let data: any = null;

  for (const date of [today, yesterday]) {
    const { data: row, error } = await supabase
      .from("daily_puzzles")
      .select(
        "id, category, difficulty, grid_size, total_words, estimated_time, variant",
      )
      .eq("puzzle_date", date)
      .eq("is_daily_challenge", true)
      .maybeSingle();

    if (!error && row) {
      data = row;
      break;
    }
  }

  // ── Step 3: No dedicated daily-challenge row found. ────────────────────────
  // The canonical daily challenge format is general/medium/10x10.
  // Search the most recent 50 rows and pick in priority order:
  //   general/medium/10x10 → any medium/10x10 → any medium → first available
  if (!data) {
    console.warn(
      "[puzzleService] No is_daily_challenge=true row found. "
      + "Falling back to general/medium/10x10 from most recent available date.",
    );

    const { data: candidates, error: candErr } = await supabase
      .from("daily_puzzles")
      .select(
        "id, category, difficulty, grid_size, total_words, estimated_time, variant, puzzle_date",
      )
      .order("puzzle_date", { ascending: false })
      .limit(50);

    if (!candErr && candidates && candidates.length > 0) {
      // Exact canonical target first
      const generalMedium10 = candidates.find(
        (c: any) => c.category === "general" && c.difficulty === "medium" && c.grid_size === 10,
      );
      const anyMedium10 = candidates.find(
        (c: any) => c.difficulty === "medium" && c.grid_size === 10,
      );
      const anyMedium = candidates.find((c: any) => c.difficulty === "medium");
      data = generalMedium10 ?? anyMedium10 ?? anyMedium ?? candidates[0];
      console.log(
        `[puzzleService] Using fallback puzzle: ${data.category}/${data.difficulty}/${data.grid_size}x${data.grid_size} from ${data.puzzle_date}`,
      );
    }
  }

  if (!data) {
    console.warn("[puzzleService] No puzzles found in DB at all.");
    return null;
  }

  // Check if this specific user has completed the resolved puzzle
  const { data: completion } = await supabase
    .from("puzzle_completions")
    .select("score, accuracy, time_taken")
    .eq("user_id", userId)
    .eq("puzzle_id", data.id)
    .maybeSingle();

  const result: PuzzleMeta = {
    id: data.id,
    category: data.category as Category,
    difficulty: data.difficulty as Difficulty,
    gridSize: data.grid_size as GridSize,
    variant: data.variant,
    totalWords: data.total_words,
    estimatedTime: data.estimated_time,
    isCompleted: !!completion,
    score: completion?.score ?? null,
    accuracy: completion?.accuracy ?? null,
    timeTaken: completion?.time_taken ?? null,
  };

  puzzleCache.set(cacheKey, result);
  return result;
}

/**
 * Fetches the live count of unique players who have completed a specific daily challenge.
 */
export async function getDailyPlayerCount(puzzleId: string): Promise<number> {
  const { count, error } = await supabase
    .from("puzzle_completions")
    .select("*", { count: "exact", head: true })
    .eq("puzzle_id", puzzleId);

  if (error) {
    console.warn(
      "[puzzleService] Failed to fetch daily player count:",
      error.message,
    );
    return 0;
  }

  return count || 0;
}

/**
 * Fetches all puzzle metadata for a given category.
 * Returns lightweight cards for the category listing screen — no full puzzle data.
 *
 * Strategy: try today (UTC) first, then search back up to 7 days to find the
 * most recent date that has puzzles for this category. This handles the rotating
 * schedule where not every category has a puzzle generated every single day.
 *
 * Optionally checks completion status for a given user ID.
 */
export async function fetchCategoryPuzzles(
  category: Category,
  userId: string = "guest",
): Promise<PuzzleMeta[]> {
  const cacheKey = `category_puzzles_${category}_${userId}`;
  const cached = puzzleCache.get<PuzzleMeta[]>(cacheKey);
  if (cached) return cached;

  const today = getTodayUTC();

  // Search the last 7 days for this category (rotating schedule means
  // not every category exists on every date).
  // Use a single range query ordered by date desc for efficiency.
  const sevenDaysAgo = (() => {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() - 7);
    return d.toISOString().split("T")[0];
  })();

  const { data: allRows, error: queryError } = await supabase
    .from("daily_puzzles")
    .select(
      "id, category, difficulty, grid_size, variant, total_words, estimated_time, puzzle_date",
    )
    .eq("category", category)
    .eq("is_daily_challenge", false)
    .gte("puzzle_date", sevenDaysAgo)
    .lte("puzzle_date", today)
    .order("puzzle_date", { ascending: false })
    .order("difficulty")
    .order("grid_size")
    .order("variant");

  if (queryError || !allRows || allRows.length === 0) {
    console.error(
      `[puzzleService] No category puzzles found for ${category} in the last 7 days.`,
      queryError?.message,
    );
    return [];
  }

  // Group rows by puzzle_date and use only the most recent date that has rows.
  const mostRecentDate = allRows[0].puzzle_date as string;
  const puzzles = allRows.filter((r: any) => r.puzzle_date === mostRecentDate);

  if (mostRecentDate !== today) {
    console.warn(
      `[puzzleService] No ${category} puzzles for today, using ${mostRecentDate} (most recent available).`,
    );
  }

  // Fetch user completions for the resolved puzzle set
  const puzzleIds = puzzles.map((p: any) => p.id);
  const { data: completions } = await supabase
    .from("puzzle_completions")
    .select("puzzle_id, score, accuracy, time_taken")
    .eq("user_id", userId)
    .in("puzzle_id", puzzleIds);

  const completionMap = new Map(
    (completions || []).map((c) => [
      c.puzzle_id,
      { score: c.score, accuracy: c.accuracy, timeTaken: c.time_taken },
    ]),
  );

  const result = puzzles.map((p: any) => {
    const completion = completionMap.get(p.id);
    return {
      id: p.id,
      category: p.category as Category,
      difficulty: p.difficulty as Difficulty,
      gridSize: p.grid_size as GridSize,
      variant: p.variant,
      totalWords: p.total_words,
      estimatedTime: p.estimated_time,
      isCompleted: !!completion,
      score: completion?.score ?? null,
      accuracy: completion?.accuracy ?? null,
      timeTaken: completion?.timeTaken ?? null,
    };
  });

  puzzleCache.set(cacheKey, result);
  return result;
}

/**
 * Returns the set of category IDs that have fresh puzzles generated for TODAY.
 * Used by the home screen to show the "NEW" freshness badge only when today's
 * puzzles are actually available (not a previous-day fallback).
 *
 * Makes a single lightweight Supabase query — no full puzzle data loaded.
 */
export async function fetchTodayAvailableCategories(): Promise<Set<string>> {
  const cacheKey = "today_available_categories";
  const cached = puzzleCache.get<Set<string>>(cacheKey);
  if (cached) return cached;

  const today = getTodayUTC();

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("category")
    .eq("puzzle_date", today)
    .eq("is_daily_challenge", false);

  if (error || !data) {
    console.warn(
      "[puzzleService] Could not determine today's available categories:",
      error?.message,
    );
    return new Set();
  }

  const categories = new Set(data.map((row) => row.category as string));
  puzzleCache.set(cacheKey, categories);
  return categories;
}

export interface ActivityItem {
  id: string; // completion ID or puzzle ID
  puzzleId: string;
  category: Category;
  difficulty: Difficulty;
  gridSize: GridSize;
  timeTaken: number;
  accuracy: number;
  completedAt: string;
}

/**
 * Fetches the user's most recent completed puzzles.
 */
export async function fetchRecentActivity(
  userId: string = "guest",
  limit: number = 3,
): Promise<ActivityItem[]> {
  const cacheKey = `recent_activity_${userId}_${limit}`;
  const cached = puzzleCache.get<ActivityItem[]>(cacheKey);
  if (cached) return cached;

  const { data, error } = await supabase
    .from("puzzle_completions")
    .select(
      `
      id,
      puzzle_id,
      time_taken,
      accuracy,
      completed_at,
      category,
      difficulty,
      grid_size
    `,
    )
    .eq("user_id", userId)
    .order("completed_at", { ascending: false })
    .limit(limit);

  if (error || !data) {
    console.warn(
      "[puzzleService] Failed to fetch recent activity:",
      error?.message,
    );
    return [];
  }

  const result = data.map((row: any) => ({
    id: row.id,
    puzzleId: row.puzzle_id || "deleted", // Provide a fallback if puzzle was cleaned up
    category: row.category as Category,
    difficulty: row.difficulty as Difficulty,
    gridSize: row.grid_size as GridSize,
    timeTaken: row.time_taken,
    accuracy: row.accuracy,
    completedAt: row.completed_at,
  }));

  puzzleCache.set(cacheKey, result);
  return result;
}

import { buildPuzzle } from "./crosswordEngine";

/**
 * Fetches the full puzzle data for a specific puzzle by ID.
 * The database only stores the word list and metadata.
 * We build the actual crossword grid layout here on the client.
 */
export async function fetchPuzzleById(
  puzzleId: string,
): Promise<Puzzle | null> {
  const cacheKey = `puzzle_${puzzleId}`;
  const cached = puzzleCache.get<Puzzle>(cacheKey);
  if (cached) return cached;

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("id, puzzle_data, category, difficulty, grid_size")
    .eq("id", puzzleId)
    .maybeSingle();

  if (error || !data) {
    console.error("[puzzleService] Failed to fetch puzzle:", error?.message);
    return null;
  }

  // data.puzzle_data is the lightweight DailyPuzzleData
  const puzzleData = data.puzzle_data;
  if (!puzzleData || !puzzleData.words) return null;

  // Build the puzzle grid dynamically on the client
  const puzzle = buildPuzzle(
    puzzleData.words,
    data.category || puzzleData.metadata?.category || "general",
    data.difficulty || puzzleData.metadata?.difficulty || "medium",
    data.grid_size || puzzleData.metadata?.gridSize || 10,
    data.id,
  );

  puzzleCache.set(cacheKey, puzzle);
  return puzzle;
}

/**
 * Fetches a specific daily puzzle by its combination of parameters.
 * Useful as a fallback when the user navigates via the old generate screen flow.
 */
export async function fetchDailyPuzzle(
  category: Category,
  difficulty: Difficulty,
  gridSize: GridSize,
  variant: number = 1,
  date?: string,
): Promise<Puzzle | null> {
  // Use the explicitly provided date as-is, or auto-select today with fallback.
  const targetDate = date || getTodayUTC();
  const isAutoDate = !date; // Only fall back when the caller didn't pin a specific date

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("id, puzzle_data")
    .eq("puzzle_date", targetDate)
    .eq("category", category)
    .eq("difficulty", difficulty)
    .eq("grid_size", gridSize)
    .eq("variant", variant)
    .maybeSingle();

  if (error || !data) {
    // If the caller pinned an explicit date, don't second-guess it.
    if (!isAutoDate) {
      console.warn(
        `[puzzleService] No daily puzzle found for ${category}/${difficulty}/${gridSize} on ${targetDate}`,
      );
      return null;
    }

    // Auto-date path: gracefully attempt yesterday's puzzle.
    console.warn(
      `[puzzleService] No daily puzzle for today (${category}/${difficulty}/${gridSize}), trying yesterday as fallback`,
    );

    const yesterday = getYesterdayUTC();
    const fallback = await supabase
      .from("daily_puzzles")
      .select("id, puzzle_data")
      .eq("puzzle_date", yesterday)
      .eq("category", category)
      .eq("difficulty", difficulty)
      .eq("grid_size", gridSize)
      .eq("variant", variant)
      .maybeSingle();

    if (fallback.error || !fallback.data) {
      console.warn(
        `[puzzleService] No puzzle found for yesterday either (${category}/${difficulty}/${gridSize}).`,
      );
      return null;
    }

    const fallbackPuzzleData = fallback.data.puzzle_data;
    if (!fallbackPuzzleData || !fallbackPuzzleData.words) return null;

    return buildPuzzle(
      fallbackPuzzleData.words,
      category,
      difficulty,
      gridSize,
      fallback.data.id,
    );
  }

  const puzzleData = data.puzzle_data;
  if (!puzzleData || !puzzleData.words) return null;

  return buildPuzzle(puzzleData.words, category, difficulty, gridSize, data.id);
}

// ─── Completion recording ────────────────────────────────────────────

/**
 * Records a puzzle completion to the server.
 * Uses upsert to handle duplicate submissions gracefully.
 *
 * Called when the player finishes a puzzle. If offline, the caller
 * should queue this and retry when connectivity is restored.
 */
export async function recordCompletion(data: CompletionData): Promise<boolean> {
  const { error } = await supabase.from("puzzle_completions").upsert(
    {
      user_id: data.userId,
      puzzle_id: data.puzzleId,
      score: data.score,
      time_taken: data.timeTaken,
      accuracy: data.accuracy,
      hints_used: data.hintsUsed,
      coins_earned: data.coinsEarned,
      puzzle_date: data.puzzleDate,
      category: data.category,
      difficulty: data.difficulty,
      grid_size: data.gridSize,
      completed_at: new Date().toISOString(),
    },
    { onConflict: "user_id,puzzle_id" },
  );

  if (error) {
    console.error(
      "[puzzleService] Failed to record completion:",
      error.message,
    );
    return false;
  }

  // Clear cache globally so the next screen fetch pulls fresh completion statuses
  puzzleCache.clear();

  return true;
}

/**
 * Fetches the user's recent completion history for the profile screen.
 * Returns the most recent completions with denormalized puzzle metadata.
 */
export async function fetchCompletionHistory(
  userId: string = "guest",
  limit: number = 20,
): Promise<CompletionData[]> {
  const { data, error } = await supabase
    .from("puzzle_completions")
    .select("*")
    .eq("user_id", userId)
    .order("completed_at", { ascending: false })
    .limit(limit);

  if (error || !data) {
    console.error("[puzzleService] Failed to fetch history:", error?.message);
    return [];
  }

  return data.map((row) => ({
    puzzleId: row.puzzle_id,
    userId: row.user_id,
    score: row.score,
    timeTaken: row.time_taken,
    accuracy: row.accuracy,
    hintsUsed: row.hints_used,
    coinsEarned: row.coins_earned,
    puzzleDate: row.puzzle_date,
    category: row.category,
    difficulty: row.difficulty,
    gridSize: row.grid_size,
  }));
}

/**
 * Fetches a specific completion record by its primary key ID and user ID.
 * Useful for the Activity review screen.
 */
export async function fetchCompletionById(
  id: string,
  userId: string = "guest",
): Promise<CompletionData | null> {
  const { data, error } = await supabase
    .from("puzzle_completions")
    .select("*")
    .eq("id", id)
    .eq("user_id", userId)
    .maybeSingle();

  if (error || !data) {
    console.warn(
      "[puzzleService] Failed to fetch completion by ID:",
      error?.message,
    );
    return null;
  }

  return {
    puzzleId: data.puzzle_id,
    userId: data.user_id,
    score: data.score,
    timeTaken: data.time_taken,
    accuracy: data.accuracy,
    hintsUsed: data.hints_used,
    coinsEarned: data.coins_earned,
    puzzleDate: data.puzzle_date,
    category: data.category,
    difficulty: data.difficulty,
    gridSize: data.grid_size,
  };
}

// ─── Leaderboard ─────────────────────────────────────────────────────

/** A single row in the global leaderboard */
export interface LeaderboardEntry {
  userId: string;
  displayName: string;
  totalScore: number;
  puzzlesSolved: number;
  streak: number;
  rank: number;
}

/**
 * Fetches the global leaderboard from the `leaderboard_view` in Supabase.
 * The view aggregates total score per user across all puzzle completions.
 *
 * @param limit - Number of top players to return (default 50)
 * @returns Ordered list of leaderboard entries, rank 1 first
 */
export async function fetchLeaderboard(
  limit: number = 50,
): Promise<LeaderboardEntry[]> {
  const cacheKey = `leaderboard_${limit}`;
  const cached = puzzleCache.get<LeaderboardEntry[]>(cacheKey);
  if (cached) return cached;

  const { data, error } = await supabase
    .from("leaderboard_view")
    .select("user_id, display_name, total_score, puzzles_solved, streak, rank")
    .order("rank", { ascending: true })
    .limit(limit);

  if (error || !data) {
    console.warn(
      "[puzzleService] Failed to fetch leaderboard:",
      error?.message,
    );
    return [];
  }

  const result: LeaderboardEntry[] = data.map((row: any) => ({
    userId: row.user_id,
    displayName: row.display_name || "Player",
    totalScore: Number(row.total_score) || 0,
    puzzlesSolved: Number(row.puzzles_solved) || 0,
    streak: Number(row.streak) || 0,
    rank: Number(row.rank) || 0,
  }));

  puzzleCache.set(cacheKey, result);
  return result;
}
