/**
 * puzzleService.ts — Client-side service for fetching pre-generated daily puzzles
 * and recording completions.
 *
 * Replaces the old client-side Gemini generation flow.
 * All puzzles come from the daily_puzzles table in Supabase,
 * pre-generated by the Edge Function cron.
 */

import { Category, Difficulty, GridSize, Puzzle } from "../types/puzzle.types";
import { supabase } from "./supabaseClient";

// ─── API Cache ───────────────────────────────────────────────────────

/**
 * Lightweight in-memory cache for API requests to minimize duplicate Supabase reads.
 * Configured for a 5-minute Time-To-Live (TTL).
 * Automatically clears when a puzzle is successfully completed.
 */
class ApiCache {
  private cache = new Map<string, { data: any; timestamp: number }>();
  private CACHE_TTL = 1000 * 60 * 5; // 5 minutes

  get<T>(key: string): T | null {
    const item = this.cache.get(key);
    if (!item) return null;
    if (Date.now() - item.timestamp > this.CACHE_TTL) {
      this.cache.delete(key);
      return null;
    }
    return item.data as T;
  }

  set(key: string, data: any): void {
    this.cache.set(key, { data, timestamp: Date.now() });
  }

  clear(): void {
    this.cache.clear();
  }
}

export const puzzleCache = new ApiCache();

// ─── Types ───────────────────────────────────────────────────────────

/** Lightweight puzzle metadata for listing screens (no full grid data) */
export interface PuzzleMeta {
  id: string;
  category: Category;
  difficulty: Difficulty;
  gridSize: GridSize;
  variant: number;
  totalWords: number;
  estimatedTime: number;
  isCompleted: boolean;
  score: number | null;
  accuracy: number | null;
  timeTaken: number | null;
}

/** Data required to record a puzzle completion */
export interface CompletionData {
  puzzleId: string;
  userId: string;
  score: number;
  timeTaken: number;
  accuracy: number;
  hintsUsed: number;
  coinsEarned: number;
  puzzleDate: string;
  category: string;
  difficulty: string;
  gridSize: number;
}

/**
 * Returns today's local date as YYYY-MM-DD.
 * Uses the device's local timezone intentionally — the generate-ahead buffer
 * on the server ensures puzzles exist for every user's local date.
 */
function getTodayLocal(): string {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  const localDate = `${year}-${month}-${day}`;
  const utcDate = d.toISOString().split("T")[0];
  return localDate;
}

// ─── Puzzle fetching ─────────────────────────────────────────────────

/**
 * Fetches today's Daily Challenge puzzle metadata for the home screen.
 * Returns null if no Daily Challenge exists for today (e.g., cron hasn't run yet).
 */
export async function fetchDailyChallenge(
  userId: string = "guest",
): Promise<PuzzleMeta | null> {
  const cacheKey = `daily_challenge_${userId}`;
  const cached = puzzleCache.get<PuzzleMeta>(cacheKey);
  if (cached) return cached;

  const today = getTodayLocal();

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select(
      "id, category, difficulty, grid_size, total_words, estimated_time, variant",
    )
    .eq("puzzle_date", today)
    .eq("is_daily_challenge", true)
    .maybeSingle();

  if (error || !data) {
    console.warn(
      "[puzzleService] No daily challenge found for today:",
      error?.message,
    );
    return null;
  }

  // Check if this specific user has completed it
  const { data: completion } = await supabase
    .from("puzzle_completions")
    .select("score, accuracy, time_taken")
    .eq("user_id", userId)
    .eq("puzzle_id", data.id)
    .maybeSingle();

  const result: PuzzleMeta = {
    id: data.id,
    category: data.category as Category,
    difficulty: data.difficulty as Difficulty,
    gridSize: data.grid_size as GridSize,
    variant: data.variant,
    totalWords: data.total_words,
    estimatedTime: data.estimated_time,
    isCompleted: !!completion,
    score: completion?.score ?? null,
    accuracy: completion?.accuracy ?? null,
    timeTaken: completion?.time_taken ?? null,
  };

  puzzleCache.set(cacheKey, result);
  return result;
}

/**
 * Fetches the live count of unique players who have completed a specific daily challenge.
 */
export async function getDailyPlayerCount(puzzleId: string): Promise<number> {
  const { count, error } = await supabase
    .from("puzzle_completions")
    .select("*", { count: "exact", head: true })
    .eq("puzzle_id", puzzleId);

  if (error) {
    console.warn(
      "[puzzleService] Failed to fetch daily player count:",
      error.message,
    );
    return 0;
  }

  return count || 0;
}

/**
 * Fetches all puzzle metadata for a given category today.
 * Returns lightweight cards for the category listing screen — no full puzzle data.
 *
 * Optionally checks completion status for a given user ID.
 */
export async function fetchCategoryPuzzles(
  category: Category,
  userId: string = "guest",
): Promise<PuzzleMeta[]> {
  const cacheKey = `category_puzzles_${category}_${userId}`;
  const cached = puzzleCache.get<PuzzleMeta[]>(cacheKey);
  if (cached) return cached;

  const today = getTodayLocal();

  // Fetch today's puzzles for this category (metadata only, no puzzle_data)
  const { data: puzzles, error: puzzleError } = await supabase
    .from("daily_puzzles")
    .select(
      "id, category, difficulty, grid_size, variant, total_words, estimated_time",
    )
    .eq("puzzle_date", today)
    .eq("category", category)
    .eq("is_daily_challenge", false)
    .order("difficulty")
    .order("grid_size")
    .order("variant");

  if (puzzleError || !puzzles) {
    console.error(
      "[puzzleService] Failed to fetch category puzzles:",
      puzzleError?.message,
    );
    return [];
  }

  // Fetch user's completions for today's puzzles in this category
  const puzzleIds = puzzles.map((p) => p.id);
  const { data: completions } = await supabase
    .from("puzzle_completions")
    .select("puzzle_id, score, accuracy, time_taken")
    .eq("user_id", userId)
    .in("puzzle_id", puzzleIds);

  const completionMap = new Map(
    (completions || []).map((c) => [
      c.puzzle_id,
      { score: c.score, accuracy: c.accuracy, timeTaken: c.time_taken },
    ]),
  );

  const result = puzzles.map((p) => {
    const completion = completionMap.get(p.id);
    return {
      id: p.id,
      category: p.category as Category,
      difficulty: p.difficulty as Difficulty,
      gridSize: p.grid_size as GridSize,
      variant: p.variant,
      totalWords: p.total_words,
      estimatedTime: p.estimated_time,
      isCompleted: !!completion,
      score: completion?.score ?? null,
      accuracy: completion?.accuracy ?? null,
      timeTaken: completion?.timeTaken ?? null,
    };
  });

  puzzleCache.set(cacheKey, result);
  return result;
}

export interface ActivityItem {
  id: string; // completion ID or puzzle ID
  puzzleId: string;
  category: Category;
  difficulty: Difficulty;
  gridSize: GridSize;
  timeTaken: number;
  accuracy: number;
  completedAt: string;
}

/**
 * Fetches the user's most recent completed puzzles.
 */
export async function fetchRecentActivity(
  userId: string = "guest",
  limit: number = 3,
): Promise<ActivityItem[]> {
  const cacheKey = `recent_activity_${userId}_${limit}`;
  const cached = puzzleCache.get<ActivityItem[]>(cacheKey);
  if (cached) return cached;

  const { data, error } = await supabase
    .from("puzzle_completions")
    .select(
      `
      id,
      puzzle_id,
      time_taken,
      accuracy,
      completed_at,
      category,
      difficulty,
      grid_size
    `,
    )
    .eq("user_id", userId)
    .order("completed_at", { ascending: false })
    .limit(limit);

  if (error || !data) {
    console.warn(
      "[puzzleService] Failed to fetch recent activity:",
      error?.message,
    );
    return [];
  }

  const result = data.map((row: any) => ({
    id: row.id,
    puzzleId: row.puzzle_id || "deleted", // Provide a fallback if puzzle was cleaned up
    category: row.category as Category,
    difficulty: row.difficulty as Difficulty,
    gridSize: row.grid_size as GridSize,
    timeTaken: row.time_taken,
    accuracy: row.accuracy,
    completedAt: row.completed_at,
  }));

  puzzleCache.set(cacheKey, result);
  return result;
}

import { buildPuzzle } from "./crosswordEngine";

/**
 * Fetches the full puzzle data for a specific puzzle by ID.
 * The database only stores the word list and metadata.
 * We build the actual crossword grid layout here on the client.
 */
export async function fetchPuzzleById(
  puzzleId: string,
): Promise<Puzzle | null> {
  const cacheKey = `puzzle_${puzzleId}`;
  const cached = puzzleCache.get<Puzzle>(cacheKey);
  if (cached) return cached;

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("id, puzzle_data, category, difficulty, grid_size")
    .eq("id", puzzleId)
    .maybeSingle();

  if (error || !data) {
    console.error("[puzzleService] Failed to fetch puzzle:", error?.message);
    return null;
  }

  // data.puzzle_data is the lightweight DailyPuzzleData
  const puzzleData = data.puzzle_data;
  if (!puzzleData || !puzzleData.words) return null;

  // Build the puzzle grid dynamically on the client
  const puzzle = buildPuzzle(
    puzzleData.words,
    data.category || puzzleData.metadata?.category || "general",
    data.difficulty || puzzleData.metadata?.difficulty || "medium",
    data.grid_size || puzzleData.metadata?.gridSize || 10,
    data.id,
  );

  puzzleCache.set(cacheKey, puzzle);
  return puzzle;
}

/**
 * Fetches a specific daily puzzle by its combination of parameters.
 * Useful as a fallback when the user navigates via the old generate screen flow.
 */
export async function fetchDailyPuzzle(
  category: Category,
  difficulty: Difficulty,
  gridSize: GridSize,
  variant: number = 1,
  date?: string,
): Promise<Puzzle | null> {
  const targetDate = date || getTodayLocal();

  const { data, error } = await supabase
    .from("daily_puzzles")
    .select("id, puzzle_data")
    .eq("puzzle_date", targetDate)
    .eq("category", category)
    .eq("difficulty", difficulty)
    .eq("grid_size", gridSize)
    .eq("variant", variant)
    .maybeSingle();

  if (error || !data) {
    console.warn(
      `[puzzleService] No daily puzzle found for ${category}/${difficulty}/${gridSize}`,
    );
    return null;
  }

  const puzzleData = data.puzzle_data;
  if (!puzzleData || !puzzleData.words) return null;

  return buildPuzzle(puzzleData.words, category, difficulty, gridSize, data.id);
}

// ─── Completion recording ────────────────────────────────────────────

/**
 * Records a puzzle completion to the server.
 * Uses upsert to handle duplicate submissions gracefully.
 *
 * Called when the player finishes a puzzle. If offline, the caller
 * should queue this and retry when connectivity is restored.
 */
export async function recordCompletion(data: CompletionData): Promise<boolean> {
  const { error } = await supabase.from("puzzle_completions").upsert(
    {
      user_id: data.userId,
      puzzle_id: data.puzzleId,
      score: data.score,
      time_taken: data.timeTaken,
      accuracy: data.accuracy,
      hints_used: data.hintsUsed,
      coins_earned: data.coinsEarned,
      puzzle_date: data.puzzleDate,
      category: data.category,
      difficulty: data.difficulty,
      grid_size: data.gridSize,
      completed_at: new Date().toISOString(),
    },
    { onConflict: "user_id,puzzle_id" },
  );

  if (error) {
    console.error(
      "[puzzleService] Failed to record completion:",
      error.message,
    );
    return false;
  }

  // Clear cache globally so the next screen fetch pulls fresh completion statuses
  puzzleCache.clear();

  return true;
}

/**
 * Fetches the user's recent completion history for the profile screen.
 * Returns the most recent completions with denormalized puzzle metadata.
 */
export async function fetchCompletionHistory(
  userId: string = "guest",
  limit: number = 20,
): Promise<CompletionData[]> {
  const { data, error } = await supabase
    .from("puzzle_completions")
    .select("*")
    .eq("user_id", userId)
    .order("completed_at", { ascending: false })
    .limit(limit);

  if (error || !data) {
    console.error("[puzzleService] Failed to fetch history:", error?.message);
    return [];
  }

  return data.map((row) => ({
    puzzleId: row.puzzle_id,
    userId: row.user_id,
    score: row.score,
    timeTaken: row.time_taken,
    accuracy: row.accuracy,
    hintsUsed: row.hints_used,
    coinsEarned: row.coins_earned,
    puzzleDate: row.puzzle_date,
    category: row.category,
    difficulty: row.difficulty,
    gridSize: row.grid_size,
  }));
}

/**
 * Fetches a specific completion record by puzzle ID and user ID.
 * Useful for the Activity review screen.
 */
export async function fetchCompletionById(
  puzzleId: string,
  userId: string = "guest",
): Promise<CompletionData | null> {
  const { data, error } = await supabase
    .from("puzzle_completions")
    .select("*")
    .eq("user_id", userId)
    .eq("puzzle_id", puzzleId)
    .maybeSingle();

  if (error || !data) {
    console.warn(
      "[puzzleService] Failed to fetch completion by ID:",
      error?.message,
    );
    return null;
  }

  return {
    puzzleId: data.puzzle_id,
    userId: data.user_id,
    score: data.score,
    timeTaken: data.time_taken,
    accuracy: data.accuracy,
    hintsUsed: data.hints_used,
    coinsEarned: data.coins_earned,
    puzzleDate: data.puzzle_date,
    category: data.category,
    difficulty: data.difficulty,
    gridSize: data.grid_size,
  };
}
