import React, { memo } from "react";
import { StyleSheet, View } from "react-native";
import { SvgXml } from "react-native-svg";
import {
  BACKDROPS,
  BackdropVariant,
} from "../../assets/brand/backdrops/backdrops.generated";

interface ScreenBackdropProps {
  variant: BackdropVariant;
}

/**
 * The ambient illustration behind a screen: soft light over a dot grid, plus
 * the screen's motif where it has one. Place it as the first child of the
 * screen's root container so everything else draws on top.
 *
 * The artwork is generated by `npm run brand` (scripts/brand/generate-brand.cjs);
 * edit it there, not in the generated module.
 */
export const ScreenBackdrop = memo(function ScreenBackdrop({
  variant,
}: ScreenBackdropProps) {
  return (
    <View style={StyleSheet.absoluteFill} pointerEvents="none">
      <SvgXml xml={BACKDROPS[variant]} width="100%" height="100%" />
    </View>
  );
});
